// packages/web-components/src/search-widget/client/components/search-result.svelte
<script>
  import { onDestroy } from 'svelte'
  import Fa from 'svelte-fa'
  import { faBed, faToilet } from '@fortawesome/free-solid-svg-icons'
  import searchWidgetStore from '../core/store'
  import { combineAddress, getPrice, combineNumberBedTypeStyle } from '../utils/results-helpers'
  import { INVALID_BACKGROUND_AS_BASE64 } from '../../../common/utils/constants'

  export let property

  let selectedProperty
  let searchType
  let propertyImages
  let bodyText
  let primaryHeading
  let secondaryHeading
  let primaryStrapline
  let secondaryStrapline
  let selectedItem

  const unsubscribeSearchWidgetStore = searchWidgetStore.subscribe(store => {
    selectedProperty = store.selectedProperty
    searchType = store.searchType
    propertyImages = store.propertyImages
    primaryHeading = store.initializers.theme.primaryHeading
    secondaryHeading = store.initializers.theme.secondaryHeading
    primaryStrapline = store.initializers.theme.primaryStrapline
    secondaryStrapline = store.initializers.theme.secondaryStrapline
    bodyText = store.initializers.theme.bodyText
    selectedItem = store.initializers.theme.selectedItem
  })

  const id = (property && property.id) || ''
  const propertyImage = propertyImages && propertyImages[id]
  const imageUrl = (propertyImage && propertyImage.url) || INVALID_BACKGROUND_AS_BASE64
  const sellingStatus = (property.selling && property.selling.status) || ''
  const lettingStatus = (property.letting && property.letting.status) || ''
  const selectedPropertyId = (selectedProperty && selectedProperty.id) || ''
  const isSelectedProperty = property.id === selectedPropertyId

  const selectProperty = () => {
    searchWidgetStore.update(store => ({
      ...store,
      selectedProperty: property,
    }))
  }

  const handleImageError = source => {
    source.src = INVALID_BACKGROUND_AS_BASE64
    source.target.src = INVALID_BACKGROUND_AS_BASE64
    source.onerror = ''
    return true
  }

  onDestroy(() => {
    unsubscribeSearchWidgetStore()
  })
</script>

<style>
  .result-item {
    box-sizing: border-box;
    cursor: pointer;
    padding: 1em;
    width: 100%;
  }

  @media screen and (min-width: 1200px) {
    .result-item {
      width: 25%;
    }
  }

  @media screen and (min-width: 960px) and (max-width: 1199px) {
    .result-item {
      width: 33.333333%;
    }
  }

  @media screen and (min-width: 768px) and (max-width: 959px) {
    .result-item {
      width: 50%;
    }
  }

  .result-item img {
    width: 100%;
    height: 12em;
  }

  .result-image-container {
    width: 100%;
    border-radius: 0.3em;
    position: relative;
    overflow: hidden;
    margin-bottom: 0.5em;
  }

  .result-offer-flag {
    background: grey;
    text-align: center;
    position: absolute;
    width: 200px;
    padding: 20px;
    top: 30px;
    right: -60px;
    transform: rotate(45deg);
    font-weight: 600;
    color: #fff;
  }

  .result-item-address-secondary {
    hyphens: auto;
    display: contents;
    display: -webkit-box;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
    text-overflow: ellipsis;
    height: 3.6em;
    line-height: 1.2em;
  }

  .result-item-pricing-text {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
  }

  .result-item-beds-text {
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
  }

  .result-item-description-text {
    display: -webkit-box;
    -webkit-line-clamp: 6;
    -webkit-box-orient: vertical;
    max-width: 700px;
    overflow: hidden;
    text-overflow: ellipsis;
    height: 8.1em;
    line-height: 1.2em;
  }

  .result-item-icon-container {
    display: flex;
    align-items: center;
  }

  .result-item-icon {
    margin-right: 0.33em;
  }

  .result-item-icon:last-child {
    margin-left: 1em;
  }
</style>

<div class="result-item" data-testid="select-property" on:click|preventDefault={selectProperty}>
  <div class="result-image-container {isSelectedProperty ? selectedItem : ''}">
    {#if sellingStatus === 'underOffer'}
      <div class="result-offer-flag">Under Offer</div>
    {/if}
    {#if lettingStatus === 'underOffer'}
      <div class="result-offer-flag">Let Agreed</div>
    {/if}
    <img alt="property image" src={imageUrl} on:error={handleImageError} />
  </div>
  <div>
    <div class={`${secondaryStrapline} result-item-address-secondary`}>
      <div class={`${secondaryHeading} result-item-address-primary`}>
        {(property.address && property.address.line1) || ''}
      </div>
      {combineAddress(property.address)}
    </div>
  </div>
  <div class={`${primaryHeading} result-item-pricing-text`}>{getPrice(property, searchType)}</div>
  <div class={`${secondaryStrapline} result-item-beds-text`}>{combineNumberBedTypeStyle(property)}</div>
  <div class={`${bodyText} result-item-description-text`}>{property.description}</div>
  <div class={`${secondaryHeading} result-item-icon-container`}>
    <span class="result-item-icon">
      <Fa icon={faBed} />
    </span>
    {property.bedrooms || 0}
    <span class="result-item-icon">
      <Fa icon={faToilet} />
    </span>
    {property.bathrooms || 0}
  </div>
</div>

// src/search-result/search-result.tsx
import * as React from 'react'
import { Loader } from '../loader'
import { oc } from 'ts-optchain';
import { AddressModel, PropertyModel } from '../types/property'
import styled from 'styled-components'
import { context } from '../context'
import { FaBed, FaToilet } from 'react-icons/fa'
import { ImgHandleError } from './img-handle-error'
import { SearchType } from '../hooks/search-store';


const { useContext } = React

const SearchResultContainer = styled.div`
  background: ${props => props.theme.colors.background};
`

const SearchResultTextContainer = styled.h1`
  color: ${props => props.theme.colors.primary};
  
  @media screen and (max-width: 1600px) {
    & {
      padding-top: 2.5rem;
    }
  }

  @media screen and (min-width: 1601px) {
    & {
      padding-left: 2.5rem;
    }
  }
  margin-top: 0;
  margin-bottom: 0;
`

const SearchResultItemContainer = styled.div`
  display: flex;
  flex-wrap: wrap;


  /* responsive desktop: 4 images */
  & > div {

    @media screen and (max-width: 1600px) {
      & {
        padding-right: 2.5rem;
      }
    }

    @media screen and (min-width: 1601px) {
      & {
        padding-left: 2.5rem;
      }
    }

    padding-top: 2.5rem;
    box-sizing: border-box;

    & > *:not(img) {
      margin-top: 0.7rem;
    }
  }

  /* 1 image in row */
  @media (max-width: 1024px) {
    & > div {
      width: 100%;
      & img {
        height: 300px
      }
    }
  }

  /* 2 images in row */
  @media (min-width: 1024px) {
      & > div {
      width: 50%;
      & img {
        height: 250px
      }
    }
  }

  /* 3 images in row */
  @media (min-width: 1800px) { 
    & > div {
      width: 33.3%;
      & img {
        height: 8vw;
      }
    }
  }

  /* 4 images in row */
  @media (min-width: 2000px) {
    & > div {
      width: 25%;
    }
  }

`

const AddressPrimaryText = styled.span`
  margin-right: 0.7rem;
  font-weight: bold;


`

const AddressSecondaryText = styled.span`
  hyphens: auto;
  display: contents;
  color: ${props => props.theme.colors.secondary};
  font-size: 1.2rem;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  max-width: 700px;
  overflow: hidden;
  text-overflow: ellipsis;
  height: 75px;
`

const PricingText = styled.span`
  color: ${props => props.theme.colors.primary};
  font-size: 1.3rem;
  font-weight: bold;
`

const NumBedTypeStyleText = styled.div`
  font-weight: bold
`

const DescriptionText = styled.div`
  display: -webkit-box;
  -webkit-line-clamp: 6;
  -webkit-box-orient: vertical;
  max-width: 700px;
  overflow: hidden;
  text-overflow: ellipsis;
  height: 130px;
  font-size: 1rem;
`

const IconContainer = styled.div`
  color: ${props => props.theme.colors.icon};
  display: flex;
  align-items: center;
  font-size: 1.2rem;

  svg {
    margin-right: 0.3rem;
  }

  svg:last-child {
    margin-left: 1rem
  }
`

const SearchResultItemDiv = styled.div`
  cursor: pointer
`

const SearchResultImageContainer = styled.div<{ isSelectedProperty: boolean }>`
  border: ${props => `2px solid ${props.theme.colors.jade}`}; 
  border-width: ${props => props.isSelectedProperty ? '2px' : '0px'};
  width: 100%;
  border-radius: 5px;
`

export const combineAdress = (address: AddressModel | undefined): string => {
  if (!address) {
    return ''
  }

  const { line3, line4, postcode } = address
  let addressString = ''
  const addressParts = [line3, line4, postcode]
  for (let i = 0; i <= addressParts.length; i++) {
    addressString += addressParts[i] || ''
    if (addressParts[i + 1] && addressParts[i + 1] !== '') {
      addressString += ', '
    }
  }


  return addressString
}

export const getPrice = (result: PropertyModel, searchType: SearchType) => {
  if (searchType === 'Rent') {
    return oc(result).letting.rent(0) + ' ' + oc(result).letting.rentFrequency('')
  }

  return oc(result).selling.qualifier('') + ' ' + oc(result).selling.price(0)
}

export const combineNumberBedTypeStyle = (result: PropertyModel) => {
  return oc(result).bedrooms(0) + ' ' + oc(result).style('') + ' ' + oc(result).type('')
}

export const SearchResult = () => {
  const searchStore = useContext(context)

  if (!searchStore) {
    return <div />
  }

  const { isLoading, searchKeyWord, getCountResult, getResultArr, searchType, propertyImages, result: rawResult, selectedProperty, setSelectedProperty } = searchStore

  if (isLoading) {
    return <Loader />
  }

  const resultArr = getResultArr()

  if (!rawResult) {
    return null
  }

  return (
    <SearchResultContainer>
      <SearchResultTextContainer>{getCountResult()} Results showing for {searchKeyWord}, for {searchType}</SearchResultTextContainer>
      <SearchResultItemContainer>
        {resultArr.map(property => {
          const id = oc(property).id("")
          const propertyImage = propertyImages[id]
          const imageUrl = oc(propertyImage).url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mN88xYAAssB20Ea4T8AAAAASUVORK5CYII=')

          const selectedPropertyId = oc(selectedProperty).id('')
          const isSelectedProperty = property.id === selectedPropertyId


          const onClick = () => {
            setSelectedProperty(property)
          }


          return (
            <SearchResultItemDiv key={property.id} onClick={onClick}>
              <SearchResultImageContainer isSelectedProperty={isSelectedProperty}>
                <ImgHandleError src={imageUrl} />
              </SearchResultImageContainer>
              <div>
                <AddressPrimaryText>{oc(property).address.line2()}</AddressPrimaryText>
                <AddressSecondaryText>{combineAdress(property.address)}</AddressSecondaryText>
              </div>
              <PricingText>{getPrice(property, searchType)}</PricingText>
              <NumBedTypeStyleText>{combineNumberBedTypeStyle(property)}</NumBedTypeStyleText>
              <DescriptionText>{property.description}</DescriptionText>
              <IconContainer>
                <FaBed /> {oc(property).bedrooms(0)}
                <FaToilet /> {oc(property).bathrooms(0)}
              </IconContainer>
            </SearchResultItemDiv>
          )
        })}
      </SearchResultItemContainer>
    </SearchResultContainer>
  )
}
